config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # NEW PRECISA VIR ANTES DE ID
  get "/tasks/new", to: "tasks#new"
  post "/tasks", to: "tasks#create"
  # GET 'LINK DPS DA /', to: ""
  get '/tasks', to: "tasks#index"
  # get 'tasks/1', to: "tasks#1"
  get "/tasks/:id", to: "tasks#show"
  # Task.all.each do |task|
  #   get "tasks/#{task.id}", to: 'tasks#task'
  # end
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
    if @task.completed
      @answer = 'Task Completed!'
    else
      @answer = 'Task Not Completed!'
    end
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.new(task_params)
    task.save # Will raise ActiveModel::ForbiddenAttributesError
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>
<ul>
<% @tasks.each do |task| %>
<li><%= link_to task.title, "tasks/#{task.id}" %></li>
<% end %>
</ul>

<h5><%= link_to "Add new Task", tasks_new_path %></h5>

app/views/tasks/new.html.erb
<h1>Create</h1>
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed, "Done?" %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>
<p></p>
<%= link_to "Back", tasks_path %>

app/views/tasks/show.html.erb
<h1><%=@task.title %></h1>
<p><i><%=@task.details%></i></p>
<p><i><strong><%= @answer%></strong></i></p>


<%= link_to "Back", tasks_path %>